parameters:

services:

# SERVICES
    service.api_key:
        class: AppBundle\Services\ApiKeyService
        arguments: ["@service_container"]

    service.wvw:
        class: AppBundle\Services\WvWService
        arguments:
            - '@service.world'
            - '@gateway.wvw'
            - '@service.cache'

    service.world:
        class: AppBundle\Services\WorldService
        arguments: ['@gateway.world']

    service.character:
        class: AppBundle\Services\CharacterService

# TOPIC
    topic.wvw:
          class: AppBundle\Services\Topic\WvWTopic
          arguments:
              - '@service.wvw'
          tags:
                     - { name: gos_web_socket.topic }

# GATEWAY
    gateway.wvw:
        class: AppBundle\Services\Gateway\WvWGateway
        arguments: ['@service.cache', '@gateway.world']

    gateway.world:
        class: AppBundle\Services\Gateway\WorldGateway
        arguments: ['@service.cache']